{{- if .Values.akash_node.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: akash-node-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "akash-node.labels" . | nindent 4 }}
data:
  node.sh: |
    #!/bin/bash
    set -x
    cat "/boot-keys/key-pass.txt" | { cat ; echo ; } | /bin/akash --home="$AKASH_HOME" keys import --keyring-backend="$AKASH_KEYRING_BACKEND"  "$AKASH_FROM" "/boot-keys/key.txt"
    /bin/akash init --chain-id "$AKASH_CHAIN_ID" "$AKASH_MONIKER"
    apt update && apt -y install curl > /dev/null 2>&1
    curl -s "$AKASH_NET/genesis.json" > "$AKASH_HOME"/config/genesis.json

    if $AKASH_NET == "https://raw.githubusercontent.com/ovrclk/net/master/mainnet"
    then
      apt -y install jq aria2 > /dev/null 2>&1
      rm -rf $AKASH_HOME/data ; mkdir -p $AKASH_HOME/data ; cd $AKASH_HOME/data
      SNAPSHOT_URL=$(curl https://cosmos-snapshots.s3.filebase.com/akash/snapshot.json | jq -r .latest)
      echo "Using latest blockchain snapshot, $SNAPSHOT_URL" ; aria2c --out=snapshot.tar.gz --summary-interval 15 --max-connection-per-server=5 $SNAPSHOT_URL
      tar -zxvf snapshot.tar.gz
      rm -f snapshot.tar.gz
    fi

    sed -i "/enable = false/c\enable = true" $AKASH_HOME/config/app.toml
    /bin/akash validate-genesis
    /bin/akash start
{{- end }}
