{{- if .Values.akash_node.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: akash-node-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "akash-node.labels" . | nindent 4 }}
data:
  node.sh: |
    #!/bin/bash
    set -x
    cat "/boot-keys/key-pass.txt" | { cat ; echo ; } | /bin/akash --home="$AKASH_HOME" keys import --keyring-backend="$AKASH_KEYRING_BACKEND"  "$AKASH_FROM" "/boot-keys/key.txt"
    /bin/akash init --chain-id "$AKASH_CHAIN_ID" "$AKASH_MONIKER"
    apt update && apt -y install curl > /dev/null 2>&1
    curl -s "$AKASH_NET/genesis.json" > "$AKASH_HOME"/config/genesis.json
    /bin/akash validate-genesis
    /bin/akash start
{{- end }}
