apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akash-node.fullname" . }}-config
  labels:
    {{- include "akash-node.labels" . | nindent 4 }}
data:
  run.sh: |
    #!/bin/bash

    set -x

    ##
    # Import key
    ##
    cat "$AKASH_BOOT_KEYS/key-pass.txt" | { cat ; echo ; } | /bin/akash --home="$AKASH_HOME" keys import --keyring-backend="$AKASH_KEYRING_BACKEND"  "$AKASH_FROM" "$AKASH_BOOT_KEYS/key.txt"

    ##
    # Run daemon
    ##
    /bin/akash init --chain-id "$AKASH_CHAIN_ID" "$AKASH_MONIKER"
    curl -s "$AKASH_NET/genesis.json" > "$AKASH_HOME"/config/genesis.json
    akash tx staking create-validator \
      --amount=1000000uakt \
      --pubkey="$(/bin/akash tendermint show-validator)" \
      --moniker="$AKASH_MONIKER" \
      --chain-id="$AKASH_CHAIN_ID" \
      --commission-rate="0.10" \
      --commission-max-rate="0.20" \
      --commission-max-change-rate="0.01" \
      --min-self-delegation="1" \
      --gas="auto" \
      --gas-prices="0.025uakt" \
      --from="$AKASH_FROM"
