apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akash-node.fullname" . }}-config
  labels:
    {{- include "akash-node.labels" . | nindent 4 }}
data:
  node.sh: |
    #!/bin/bash
    set -x
    cat "$AKASH_BOOT_KEYS/key-pass.txt" | { cat ; echo ; } | /bin/akash --home="$AKASH_HOME" keys import --keyring-backend="$AKASH_KEYRING_BACKEND"  "$AKASH_FROM" "$AKASH_BOOT_KEYS/key.txt"
    /bin/akash init --chain-id "$AKASH_CHAIN_ID" "$AKASH_MONIKER"
    apt update && apt -y install curl > /dev/null 2>&1
    curl -s "$AKASH_NET/genesis.json" > "$AKASH_HOME"/config/genesis.json
    /bin/akash validate-genesis
    /bin/akash tendermint show-node-id > /data/node-$NODE.id
    SEEDS=""
    for i in $(seq 1 4); do 
      while [ ! -f /data/node-${i}.id ]; do sleep 1; done
      ID=$(cat /data/node-${i}.id)
      ADDRESS="${ID}@127.0.0.1:2665${i}"
      SEEDS="${ADDRESS},${SEEDS}"
    done
    export AKASH_P2P_PRIVATE_PEER_IDS=${SEEDS%?}
    export AKASH_RPC_LADDR=tcp://127.0.0.1:2666${NODE}
    export AKASH_P2P_LADDR=tcp://127.0.0.1:2665${NODE}
    export AKASH_PROF_LADDR=tcp://127.0.0.1:606${NODE}
    epxort AKASH_RPC_GRPC_LADDR=tcp://127.0.0.1:909${NODE}
    /bin/akash start
