{{- range untilStep 1 5 1 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akash-node-{{ . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: akash-node
    akash.network/node: "{{ . }}"
spec:
{{- if not $.Values.autoscaling.enabled }}
  replicas: {{ $.Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: akash-node
      akash.network/node: "{{ . }}"
  template:
    metadata:
    {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: akash-node
        akash.network/node: "{{ . }}"
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: akash-node
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          command: [ "/bin/sh" , "/config/node.sh" ]
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:   
            - name: NODE
              value: "{{ . }}"
            - name: AKASH_BOOT_KEYS
              value: /boot-keys
            - name: AKASH_MONIKER
              value: {{ $.Values.akash_node.moniker }}-{{ . }}
            - name: AKASH_NET
              value: {{ $.Values.akash_node.net }}
            - name: AKASH_HOME
              value: {{ $.Values.akash_node.home }}
            - name: AKASH_FROM
              value: {{ $.Values.akash_node.from }}
            - name: AKASH_CHAIN_ID
              value: {{ $.Values.akash_node.chain_id }}
            - name: AKASH_KEYRING_BACKEND
              value: {{ $.Values.akash_node.keyring_backend }}
            - name: AKASH_P2P_PERSISTENT_PEERS
              value: {{ $.Values.akash_node.peers }}
          ports:
            - containerPort: 26656
              name: akashd-p2p
            - containerPort: 26657
              name: akashd-rpc
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: keys
              mountPath: /boot-keys
              readOnly: true
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: akash-node-config
        - name: keys
          secret:
            secretName: akash-node-keys
{{- end }}
