 {{if not (default .Values.bootstrap.enabled true)}}
---
apiVersion: v1
kind: Service
metadata:
  name: akash-node-1
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 26656
      name: akashd-p2p
    - port: 26657
      name: akashd-rpc
  selector:
    akash.network/node: "1"
{{ end }}
