apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "akash-node.fullname" . }}
  labels:
    {{- include "akash-node.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: "128Gi"
