apiVersion: v1
kind: ConfigMap
metadata:
  name: akash-provider-boot
data:
  run.sh: |
    #!/bin/bash

    set -x

    env | sort

    cat $AKASH_BOOT_KEYS/key.txt
    cat $AKASH_BOOT_KEYS/key-pass.txt

    ##
    # Import key
    ##
    cat "$AKASH_BOOT_KEYS/key-pass.txt" | { cat ; echo ; } | /bin/akash --home="$AKASH_HOME" keys import --keyring-backend="$AKASH_KEYRING_BACKEND"  "$AKASH_FROM" "$AKASH_BOOT_KEYS/key.txt"

    ##
    # Run daemon
    ##
    #/akash --home=$AKASH_HOME provider run --cluster-k8s
    /bin/akash --home="$AKASH_HOME" --node="$AKASH_NODE" --chain-id="$AKASH_CHAIN_ID" --keyring-backend="$AKASH_KEYRING_BACKEND" --from="$AKASH_FROM" provider run --cluster-k8s

    sleep 3600
