apiVersion: v1
kind: ConfigMap
metadata:
  name: akash-provider-boot
data:
  run.sh: |
    #!/bin/sh

    set -e

    env | sort

    sed 's/\"//g' $AKASH_BOOT_KEYS/key.txt > /tmp/key.txt
    sed 's/\"//g' $AKASH_BOOT_KEYS/key-pass.txt > /tmp/key-pass.txt

    cat $AKASH_BOOT_KEYS/key.txt
    cat $AKASH_BOOT_KEYS/key-pass.txt

    cat /tmp/key.txt
    cat /tmp/key-pass.txt

    ##
    # Import key
    ##
    /bin/akash --home="$AKASH_HOME" keys import --keyring-backend="$AKASH_KEYRING_BACKEND"  "$AKASH_FROM" "/tmp/key.txt" < "/tmp/key-pass.txt"

    ##
    # Run daemon
    ##
    #/akash --home=$AKASH_HOME provider run --cluster-k8s
    /bin/akash --home="$AKASH_HOME" --node="$AKASH_NODE" --chain-id="$AKASH_CHAIN_ID" --keyring-backend="$AKASH_KEYRING_BACKEND" --from="$AKASH_FROM" provider run --cluster-k8s
