apiVersion: v1
kind: Secret
metadata:
  name: akash-provider-keys
type: "Opaque"
data:
  provider-cert.pem: |
    {{ indent 2 .Values.akash_provider.providercert }}
  key.txt: |
    {{ indent 2 .Values.akash_client.key }}
  key-pass.txt: "{{ .Values.akash_client.keysecret }}"
