apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  8443: "akash-services/akash-provider:8443"
  1317: "akash-services/akash-node-1:1317"
  9090: "akash-services/akash-node-1:9090"
  26656: "akash-services/akash-node-1:26656"
  26657: "akash-services/akash-node-1:26657"
