apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "akash-ingress.fullname" . }}
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: provider.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: akash-provider
                port:
                  number: 8443

    - host: p2p.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: akash-node-1
                port:
                  number: 26656

    - host: rpc.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: akash-node-1
                port:
                  number: 26657
