apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "akash-ingress.fullname" . }}-node-rpc
  namespace: akash-services
  annotations:
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: rpc.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: akash-node-1
                port:
                  number: 26657
