apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventory-operator.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $val := .Values.akash_provider }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
