apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  8443: "{{ .Release.Namespace }}/{{ include "provider.fullname" . }}:8443"
  26656: "{{ .Release.Namespace }}/akash-node-1:26656"
