{{- if .Values.bids.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "provider.fullname" . }}-bids
  namespace: {{ .Release.Namespace }}
data:
  bid_on_storage.sh: |
    #!/bin/bash

    set -euo pipefail

    # min amount of storage, otherwise skip bidding
    STORAGE_MINIMUM=274877906943

    # cost per byte of storage
    STORAGE_SCALE=0.1 
    # cost per whole CPU
    CPU_SCALE=2.0
    # cost per byte of RAM
    MEMORY_SCALE=0.345

    data_in=$(jq .)

    memory_total=$(echo "$data_in" | jq 'map(.memory * .count) | add')
    cpu_total=$(echo "$data_in" | jq 'map(.cpu * .count) | add')
    storage_total=$(echo "$data_in" | jq 'map(.storage * .count) | add')

    # check that the minimum amount of storage is met
    if [[ $STORAGE_MINIMUM -gt $storage_total ]]; then
      echo '0' # do not bid
      exit 0
    fi

    # bid
    echo "($memory_total * $MEMORY_SCALE) + ($storage_total * $STORAGE_SCALE) + ($cpu_total * $CPU_SCALE)" | bc
{{- end }}
