apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "provider.fullname" . }}-client-config
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $val := .Values.akash_client }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
