apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: storageclassinfos.akash.network
spec:
  group: akash.network
  scope: Cluster
  names:
    plural: storageclassinfos
    singular: storageclassinfo
    kind: StorageClassInfo
    shortNames:
      - sci
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                capacity:
                  type: integer
                  format: int64
                  default: -1
                  minimum: -1