apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: akash-provider
  namespace:  {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: provider.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "provider.fullname" . }}
                port:
                  name: api
