apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "inventory-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  rules:
    - host: {{ include "inventory-operator.fullname" . }}.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "inventory-operator.fullname" . }}
                port:
                  name: gateway
