# Default values for provider.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/ovrclk/akash
  pullPolicy: IfNotPresent
  tag: 0.14.1

from:
key:
keysecret:
chainid: akashnet-2
domain:
home: "/root/.akash"
node: "http://akash.c29r3.xyz:80/rpc"
keyringbackend: "test"
trustnode: "true"

# Important to know about the gas and fees:
#
# fees = (gas * gas-prices) as per Cosmos SDK docs.
# (200000 * 0.025uakt) = 5000uakt floor fee for most of RPC nodes.
#
# Akash RPC nodes set --minimum-gas-prices=0.25uakt which gives
# 5000uakt minimum fee when multiplied by the gas price (200000 default).
#
# Akash clients should respect this and set --minimum-gas-prices to 0.25uakt
#
# Note that RPC node running without minimum-gas-prices set will accept
# 0uakt fee transactions which is not desirable as per Cosmos SDK docs.
#
# --gas argument works only when --minimum-gas-prices is set!
# Note that the clients cannot provide both fees and gas prices!
#
# Anything you set here will get globally exposed via AKASH_MINIMUM_GAS_PRICES,
# AKASH_GAS, AKASH_GAS_ADJUSTMENT environment variables in
# charts/akash-provider/templates/deployment.yaml
minimum_gas_prices: "0.25uakt"
gas: "auto"
gasadjustment: "1.3"

bids:
  enabled: false
bidpricestrategy: "scale"
bidpricecpuscale: "0.004"
bidpricememoryscale: "0.0016"
bidpriceendpointscale: "0"
bidpricestoragescale: "0.00016"
withdrawalperiod: "24h"

attributes:
  - key: region
    value: us-west
  - key: host
    value: akash
  - key: tier
    value: community
  - key: organization
    value: akash.network

debug: "false"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
