apiVersion: v1
kind: Service
metadata:
  name: {{ include "akash-hostname-operator.fullname" . }}
  labels:
    {{- include "akash-hostname-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: status
  selector:
    {{- include "akash-hostname-operator.selectorLabels" . | nindent 4 }}
