apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akash-e2e.fullname" . }}-cron
  namespace: {{ .Release.Namespace }}
data:
  run.sh: |
    #!/bin/bash
    set -x
    cat /boot-keys/key-pass.txt | { cat ; echo ; } | /bin/akash keys import primary /boot-keys/primary-key.pem
    cat /boot-keys/key-pass.txt | { cat ; echo ; } | /bin/akash keys import check_0 /boot-keys/check-0-key.pem
    cat /boot-keys/key-pass.txt | { cat ; echo ; } | /bin/akash keys import check_1 /boot-keys/check-1-key.pem
    cat /boot-keys/key-pass.txt | { cat ; echo ; } | /bin/akash keys import check_2 /boot-keys/check-2-key.pem
    cat /boot-keys/key-pass.txt | { cat ; echo ; } | /bin/akash keys import check_3 /boot-keys/check-3-key.pem
    cd /venv && source ./bin/activate
    python -m akashnines.monitor
    if $AKASH_DEBUG == "true"; then sleep 5000; fi
