apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "akash-e2e.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: monitor
            image: sacreman/akashnines:latest
            imagePullPolicy: IfNotPresent
            command: ["/bin/bash", "/boot/run.sh"]
            env:
                - name: AKASH_DEBUG
                value: "{{ $.Values.debug }}"
                - name: AKASH_PATH
                value: "/bin/akash"
                - name: AKASH_KEYRING_BACKEND
                value: "test"
                - name: POSTGRES_URL
                value: "postgres://akashnines:password@{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc:5432/akashnines"
                - name: CHAIN_ID
                value: "{{ $.Values.chainid }}"
                - name: RPC_NODE
                value: "{{ $.Values.node }}"
                - name: WALLET_HOME
                value: "/root/.akash"
                - name: GAS_PRICES
                value: "{{ $.Values.gasprices }}"
                - name: GAS
                value: "{{ $.Values.gas }}"
                - name: MINIMUM_UAKT_BALANCE
                value: "{{ $.Values.minuaktbalance }}"
                - name: CRITICAL_PROVIDERS
                value: "{{ $.Values.criticalproviders }}"
                - name: BUCKET_NAME
                value: "none"
            volumeMounts:
            - name: boot
              mountPath: /boot
              readOnly: true
            - name: keys
              mountPath: /boot-keys
              readOnly: true
          restartPolicy: OnFailure
      volumes:
        - name: boot
          configMap:
            name: {{ include "akash-e2e.fullname" . }}-cron
        - name: keys
          secret:
            secretName: {{ include "akash-e2e.fullname" . }}-keys
