apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akash-e2e.fullname" . }}-keys
  namespace: {{ .Release.Namespace }}
type: "Opaque"
data:
  key-pass.txt: {{ .Values.keysecret | quote }}
  primary-key.pem: {{ .Values.primarykey | quote }}
  check-0-key.pem: {{ .Values.check0key | quote }}
  check-1-key.pem: {{ .Values.check1key | quote }}
  check-2-key.pem: {{ .Values.check2key | quote }}
  check-3-key.pem: {{ .Values.check3key | quote }}
