apiVersion: v1
kind: Service
metadata:
  name: {{ include "akash-e2e.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: akash-e2e
    {{- include "akash-e2e.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: http
  selector:
    app: {{ include "akash-e2e.fullname" . }}
    {{- include "akash-e2e.selectorLabels" . | nindent 4 }}
