apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "akash-e2e.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "akash-e2e.labels" . | nindent 4 }}
automountServiceAccountToken: true
