apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: from-akash
  namespace: metallb-system
spec:
  podSelector:
    matchLabels:  
      app: metallb
      component: controller
  policyTypes:
  - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: akash-services
        podSelector: 
          matchLabels: {}
