{{- if .Values.controller.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "akash-metallb.controller.serviceAccountName" . }}
  labels:
    {{- include "akash-metallb.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.speaker.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "akash-metallb.speaker.serviceAccountName" . }}
  labels:
    {{- include "akash-metallb.labels" . | nindent 4 }}
    app.kubernetes.io/component: speaker
  {{- with .Values.speaker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
