apiVersion: v1
kind: Service
metadata:
  labels:
    component: controller
  name: controller
  namespace: metallb-system
spec:
  selector:
    component: controller
    app: metallb
  ports:
    - protocol: TCP
      name: monitoring
      port: 7472
