apiVersion: v1
kind: Service
metadata:
  labels:
    component: controller
  name: controller
  namespace: metallb-system
spec:
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: akash-metallb
    app.kubernetes.io/name: akash-metallb
  ports:
    - protocol: TCP
      name: monitoring
      port: 7472
