apiVersion: apps/v1
kind: Deployment
metadata:
  name: akash-ip-operator
  namespace: akash-services
  labels:
    akash.network/component: akash-ip-operator
spec:
  selector:
    matchLabels:
      app: akash-ip-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: akash-ip-operator
        akash.network/component: akash-ip-operator
    spec:
      serviceAccountName: akash-ip-operator
      containers:
      - name: akash-ip-operator
        image: ghcr.io/ovrclk/akash:stable
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "exec", "/bin/akash", "provider", "ip-operator"]
        ports:
          - name: api
            containerPort: 8086
        env:
          - name: AKASH_K8S_MANIFEST_NS
            value: "lease"
          - name: AKASH_PRUNE_INTERVAL
            value: "600s"
          - name: AKASH_IGNORE_LIST_ENTRY_LIMIT
            value: "131072"
          - name: AKASH_WEB_REFRESH_INTERVAL
            value: "5s"
          - name: AKASH_RETRY_DELAY
            value: "3s"
          - name: AKASH_IGNORE_LIST_AGE_LIMIT
            value: "2613600s"
          - name: AKASH_EVENT_FAILURE_LIMIT
            value: "3"
          - name: AKASH_PROVIDER
            value: "{{ .Values.provider_address }}"
