---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "inventory-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    akash.network: "true"
    app.kubernetes.io/name: akash
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/component: operator
    {{- include "inventory-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
      - nodes
      - pods
      - events
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ceph.rook.io
    resources:
      - cephclusters
      - cephblockpools
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - akash.network
    resources:
      - inventoryrequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - akash.network
    resources:
      - inventories
    verbs:
      - create
      - patch
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "inventory-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    akash.network: "true"
    app.kubernetes.io/name: akash
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/component: operator
    {{- include "inventory-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: inventory-operator
subjects:
  - kind: ServiceAccount
    name: inventory-operator
    namespace: {{ .Release.Namespace }}
