apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventory-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    akash.network: "true"
    app.kubernetes.io/name: akash
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/component: operator
    {{- include "inventory-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      appProtocol: http
      name: api
  selector:
    app.kubernetes.io/name: akash
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/component: operator
    {{- include "inventory-operator.selectorLabels" . | nindent 4 }}
