debug: true

keysecret:
primarykey:
check0key:
check1key:
check2key:
check3key:

serviceAccount:
    create: true

postgresql:
    auth:
        username: akashnines
        password: password
        database: akashnines
    primary:
        podSecurityContext:
            enabled: false
            fsGroup: ""
        containerSecurityContext:
            enabled: false
            runAsUser: "auto"

    readReplicas:
        podSecurityContext:
            enabled: false
            fsGroup: ""
        containerSecurityContext:
            enabled: false
            runAsUser: "auto"

    volumePermissions:
        enabled: false
        securityContext:
            runAsUser: "auto"
